[2025-05-27T11:31:57.119+0000] {processor.py:186} INFO - Started process (PID=13384) to work on /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:31:57.120+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/_step1_slurm_20250527T113120.py for tasks to queue
[2025-05-27T11:31:57.123+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:31:57.122+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:31:57.136+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:31:57.132+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/_step1_slurm_20250527T113120.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/_step1_slurm_20250527T113120.py", line 18, in <module>
    slurm = SubmitAndMonitorSlurmJobOperator(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 491, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sbatch_args'
[2025-05-27T11:31:57.137+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:31:57.160+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/_step1_slurm_20250527T113120.py took 0.052 seconds
[2025-05-27T11:32:27.828+0000] {processor.py:186} INFO - Started process (PID=13452) to work on /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:32:27.831+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/_step1_slurm_20250527T113120.py for tasks to queue
[2025-05-27T11:32:27.834+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:32:27.833+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:32:27.841+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:32:27.839+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/_step1_slurm_20250527T113120.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/_step1_slurm_20250527T113120.py", line 18, in <module>
    slurm = SubmitAndMonitorSlurmJobOperator(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 491, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sbatch_args'
[2025-05-27T11:32:27.842+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:32:27.863+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/_step1_slurm_20250527T113120.py took 0.042 seconds
[2025-05-27T11:32:57.914+0000] {processor.py:186} INFO - Started process (PID=13521) to work on /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:32:57.915+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/_step1_slurm_20250527T113120.py for tasks to queue
[2025-05-27T11:32:57.919+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:32:57.919+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:32:57.926+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:32:57.924+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/_step1_slurm_20250527T113120.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/_step1_slurm_20250527T113120.py", line 18, in <module>
    slurm = SubmitAndMonitorSlurmJobOperator(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 491, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sbatch_args'
[2025-05-27T11:32:57.927+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:32:57.948+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/_step1_slurm_20250527T113120.py took 0.040 seconds
[2025-05-27T11:33:28.667+0000] {processor.py:186} INFO - Started process (PID=13590) to work on /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:33:28.668+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/_step1_slurm_20250527T113120.py for tasks to queue
[2025-05-27T11:33:28.675+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:33:28.674+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:33:28.689+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:33:28.685+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/_step1_slurm_20250527T113120.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/_step1_slurm_20250527T113120.py", line 18, in <module>
    slurm = SubmitAndMonitorSlurmJobOperator(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 491, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sbatch_args'
[2025-05-27T11:33:28.690+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:33:28.718+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/_step1_slurm_20250527T113120.py took 0.072 seconds
[2025-05-27T11:33:58.760+0000] {processor.py:186} INFO - Started process (PID=13659) to work on /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:33:58.761+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/_step1_slurm_20250527T113120.py for tasks to queue
[2025-05-27T11:33:58.765+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:33:58.764+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:33:58.771+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:33:58.769+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/_step1_slurm_20250527T113120.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/_step1_slurm_20250527T113120.py", line 18, in <module>
    slurm = SubmitAndMonitorSlurmJobOperator(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 491, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sbatch_args'
[2025-05-27T11:33:58.772+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:33:58.791+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/_step1_slurm_20250527T113120.py took 0.038 seconds
[2025-05-27T11:34:28.955+0000] {processor.py:186} INFO - Started process (PID=13726) to work on /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:34:28.957+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/_step1_slurm_20250527T113120.py for tasks to queue
[2025-05-27T11:34:28.962+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:34:28.961+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:34:28.972+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:34:28.969+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/_step1_slurm_20250527T113120.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/_step1_slurm_20250527T113120.py", line 18, in <module>
    slurm = SubmitAndMonitorSlurmJobOperator(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 491, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sbatch_args'
[2025-05-27T11:34:28.973+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:34:28.998+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/_step1_slurm_20250527T113120.py took 0.057 seconds
[2025-05-27T11:34:59.296+0000] {processor.py:186} INFO - Started process (PID=13795) to work on /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:34:59.297+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/_step1_slurm_20250527T113120.py for tasks to queue
[2025-05-27T11:34:59.302+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:34:59.301+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:34:59.310+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:34:59.308+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/_step1_slurm_20250527T113120.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/_step1_slurm_20250527T113120.py", line 18, in <module>
    slurm = SubmitAndMonitorSlurmJobOperator(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 491, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sbatch_args'
[2025-05-27T11:34:59.311+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:34:59.341+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/_step1_slurm_20250527T113120.py took 0.057 seconds
[2025-05-27T11:35:29.487+0000] {processor.py:186} INFO - Started process (PID=13864) to work on /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:35:29.488+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/_step1_slurm_20250527T113120.py for tasks to queue
[2025-05-27T11:35:29.491+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:35:29.491+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:35:29.499+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:35:29.497+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/_step1_slurm_20250527T113120.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/_step1_slurm_20250527T113120.py", line 18, in <module>
    slurm = SubmitAndMonitorSlurmJobOperator(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 491, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sbatch_args'
[2025-05-27T11:35:29.500+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:35:29.520+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/_step1_slurm_20250527T113120.py took 0.039 seconds
[2025-05-27T11:35:59.845+0000] {processor.py:186} INFO - Started process (PID=13933) to work on /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:35:59.846+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/_step1_slurm_20250527T113120.py for tasks to queue
[2025-05-27T11:35:59.851+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:35:59.850+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:35:59.864+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:35:59.860+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/_step1_slurm_20250527T113120.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/_step1_slurm_20250527T113120.py", line 18, in <module>
    slurm = SubmitAndMonitorSlurmJobOperator(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 491, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sbatch_args'
[2025-05-27T11:35:59.865+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:35:59.900+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/_step1_slurm_20250527T113120.py took 0.066 seconds
[2025-05-27T11:36:30.248+0000] {processor.py:186} INFO - Started process (PID=14002) to work on /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:36:30.249+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/_step1_slurm_20250527T113120.py for tasks to queue
[2025-05-27T11:36:30.254+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:36:30.253+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:36:30.263+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:36:30.261+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/_step1_slurm_20250527T113120.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/_step1_slurm_20250527T113120.py", line 18, in <module>
    slurm = SubmitAndMonitorSlurmJobOperator(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 491, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sbatch_args'
[2025-05-27T11:36:30.265+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:36:30.292+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/_step1_slurm_20250527T113120.py took 0.055 seconds
[2025-05-27T11:37:00.441+0000] {processor.py:186} INFO - Started process (PID=14071) to work on /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:37:00.442+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/_step1_slurm_20250527T113120.py for tasks to queue
[2025-05-27T11:37:00.444+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:37:00.444+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:37:00.451+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:37:00.449+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/_step1_slurm_20250527T113120.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/_step1_slurm_20250527T113120.py", line 18, in <module>
    slurm = SubmitAndMonitorSlurmJobOperator(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 491, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sbatch_args'
[2025-05-27T11:37:00.451+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:37:00.471+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/_step1_slurm_20250527T113120.py took 0.037 seconds
[2025-05-27T11:37:30.965+0000] {processor.py:186} INFO - Started process (PID=14139) to work on /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:37:30.966+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/_step1_slurm_20250527T113120.py for tasks to queue
[2025-05-27T11:37:30.969+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:37:30.968+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:37:30.976+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:37:30.974+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/_step1_slurm_20250527T113120.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/_step1_slurm_20250527T113120.py", line 18, in <module>
    slurm = SubmitAndMonitorSlurmJobOperator(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 491, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sbatch_args'
[2025-05-27T11:37:30.979+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:37:31.002+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/_step1_slurm_20250527T113120.py took 0.045 seconds
[2025-05-27T11:38:01.598+0000] {processor.py:186} INFO - Started process (PID=14206) to work on /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:38:01.600+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/_step1_slurm_20250527T113120.py for tasks to queue
[2025-05-27T11:38:01.604+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:38:01.603+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:38:01.613+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:38:01.609+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/_step1_slurm_20250527T113120.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/_step1_slurm_20250527T113120.py", line 18, in <module>
    slurm = SubmitAndMonitorSlurmJobOperator(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 491, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sbatch_args'
[2025-05-27T11:38:01.614+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:38:01.637+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/_step1_slurm_20250527T113120.py took 0.051 seconds
[2025-05-27T11:38:31.794+0000] {processor.py:186} INFO - Started process (PID=14275) to work on /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:38:31.795+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/_step1_slurm_20250527T113120.py for tasks to queue
[2025-05-27T11:38:31.798+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:38:31.798+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:38:31.806+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:38:31.804+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/_step1_slurm_20250527T113120.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/_step1_slurm_20250527T113120.py", line 18, in <module>
    slurm = SubmitAndMonitorSlurmJobOperator(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 491, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sbatch_args'
[2025-05-27T11:38:31.807+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:38:31.828+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/_step1_slurm_20250527T113120.py took 0.044 seconds
[2025-05-27T11:39:02.367+0000] {processor.py:186} INFO - Started process (PID=14344) to work on /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:39:02.368+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/_step1_slurm_20250527T113120.py for tasks to queue
[2025-05-27T11:39:02.372+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:39:02.371+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:39:02.380+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:39:02.377+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/_step1_slurm_20250527T113120.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/_step1_slurm_20250527T113120.py", line 18, in <module>
    slurm = SubmitAndMonitorSlurmJobOperator(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 491, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sbatch_args'
[2025-05-27T11:39:02.380+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:39:02.399+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/_step1_slurm_20250527T113120.py took 0.044 seconds
[2025-05-27T11:39:32.625+0000] {processor.py:186} INFO - Started process (PID=14413) to work on /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:39:32.626+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/_step1_slurm_20250527T113120.py for tasks to queue
[2025-05-27T11:39:32.630+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:39:32.629+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:39:32.639+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:39:32.636+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/_step1_slurm_20250527T113120.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/_step1_slurm_20250527T113120.py", line 18, in <module>
    slurm = SubmitAndMonitorSlurmJobOperator(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 491, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sbatch_args'
[2025-05-27T11:39:32.640+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:39:32.662+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/_step1_slurm_20250527T113120.py took 0.048 seconds
[2025-05-27T11:40:03.349+0000] {processor.py:186} INFO - Started process (PID=14482) to work on /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:40:03.351+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/_step1_slurm_20250527T113120.py for tasks to queue
[2025-05-27T11:40:03.353+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:40:03.353+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:40:03.362+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:40:03.358+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/_step1_slurm_20250527T113120.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/_step1_slurm_20250527T113120.py", line 18, in <module>
    slurm = SubmitAndMonitorSlurmJobOperator(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 491, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sbatch_args'
[2025-05-27T11:40:03.363+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:40:03.388+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/_step1_slurm_20250527T113120.py took 0.048 seconds
[2025-05-27T11:40:33.863+0000] {processor.py:186} INFO - Started process (PID=14551) to work on /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:40:33.864+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/_step1_slurm_20250527T113120.py for tasks to queue
[2025-05-27T11:40:33.867+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:40:33.867+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:40:33.874+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:40:33.872+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/_step1_slurm_20250527T113120.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/_step1_slurm_20250527T113120.py", line 18, in <module>
    slurm = SubmitAndMonitorSlurmJobOperator(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 491, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sbatch_args'
[2025-05-27T11:40:33.875+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:40:33.894+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/_step1_slurm_20250527T113120.py took 0.040 seconds
[2025-05-27T11:41:04.477+0000] {processor.py:186} INFO - Started process (PID=14620) to work on /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:41:04.478+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/_step1_slurm_20250527T113120.py for tasks to queue
[2025-05-27T11:41:04.481+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:41:04.480+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:41:04.487+0000] {logging_mixin.py:190} INFO - [2025-05-27T11:41:04.485+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/_step1_slurm_20250527T113120.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/_step1_slurm_20250527T113120.py", line 18, in <module>
    slurm = SubmitAndMonitorSlurmJobOperator(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 491, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sbatch_args'
[2025-05-27T11:41:04.488+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/_step1_slurm_20250527T113120.py
[2025-05-27T11:41:04.509+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/_step1_slurm_20250527T113120.py took 0.042 seconds
